// frontend/src/poll/Statistics.tsx
import * as d3 from 'd3';
import {OptionData} from '../App';

interface StatisticsProps {
    options: OptionData[]
    setSelectedSlice: (str: string) => void
}

interface PieChartProps {
    data: OptionData[]
    voteSum: number
    setSelectedSlice: (str: string) => void
 }


const Statistics = (props: StatisticsProps) => {
    let voteSum = 0
    
    const data = props.options.filter(option => option.votes > 0 && option.approved).map(option => {
        voteSum += option.votes

        let title = option.optionTitle
        if (title.length > 10)
            title = title.substring(0, 10) + "...";

        return {
            "approved": true, //only approved allowed
            "optionTitle": title,
            "votes": option.votes,
            "_id": option._id
        }
    });

    if (data.length === 0)
        return null;

    return (<div className="w-full p-5 h-fit mx-auto">
            <svg className="w-1/2 h-full mx-auto" viewBox="0 0 400 400" preserveAspectRatio="xMidYMid meet">
                <g transform="translate(200,200)">
                    <PieChart data={data} voteSum = {voteSum} setSelectedSlice = {props.setSelectedSlice} />
                </g>
            </svg>
        </div>)
}




const PieChart = (props: PieChartProps) => {
    const colors = d3.scaleOrdinal(["#c2d9f2","#afcbe6","#7dbbf5","#76a7d6","#72cae0","#88d4d9"]);

    const radius = 200

    const pie = d3.pie<OptionData>().value((d: any) => d.votes)

    const arc = d3.arc<d3.PieArcDatum<OptionData>>()
        .innerRadius(80)
        .outerRadius(radius)

        
    const arcs = pie(props.data)

    //labels
    const labelArc = d3.arc<d3.PieArcDatum<OptionData>>()
        .outerRadius(radius - 60)
        .innerRadius(radius - 60);


    //center text
    const centerText = d3.arc<d3.PieArcDatum<OptionData>>()
        .innerRadius(0)
        .outerRadius(0);



    return (
        <g>
            {arcs.map((d, i) => (
                <g key={i} onMouseEnter = {() => {props.setSelectedSlice(d.data["_id"])}} onMouseLeave = {() => {props.setSelectedSlice("")}} className = "cursor-crosshair">
                    <path d={arc(d) ?? ""} fill={i === arcs.length - 1 && colors(i + '') === colors("0") ? colors((i + 1) + '') : colors(i + '')} />
                    <text transform={`translate(${labelArc.centroid(d)})`} textAnchor="middle" fill="black" fontSize="14px">{`${d.data.optionTitle} (${Math.round((d.data.votes / props.voteSum) * 100)}%)`}</text>
                </g>
            ))}

            <text transform={`translate(${centerText.centroid(arcs[0])})`} textAnchor="middle" fill="white" fontSize="20px">{`${props.voteSum} ${props.voteSum === 1 ? "vote" : "votes"}`}</text>
        </g>
    )

}



export default Statistics

// frontend/src/app/components/poll/statistics/statistics.component.ts
import { Component, EventEmitter, Input, Output, SimpleChanges } from '@angular/core';
import { PieArcDatum, Option } from 'src/app/types/types';
import * as d3 from 'd3';

@Component({
  selector: 'statistics',
  templateUrl: './statistics.component.html',
})
export class StatisticsComponent {
  @Input() options!: Option[];
  @Output() setSelectedSlice = new EventEmitter<string>();

  setSlice(optionId: string) {
    this.setSelectedSlice.emit(optionId);
  }

  RADIUS = 200;
  voteSum: number = 0;

  data: Option[] = [];
  arcs: PieArcDatum[] = [];
  arc = d3
    .arc<PieArcDatum>()
    .innerRadius(80)
    .outerRadius(this.RADIUS);
  
  colors = d3.scaleOrdinal([
      '#c2d9f2',
      '#afcbe6',
      '#7dbbf5',
      '#76a7d6',
      '#72cae0',
      '#88d4d9',
    ]);

  constructPie() {
    this.voteSum = 0;

    //filter data, truncate titles, count votes
    this.data = this.options
      .filter((option) => option.votes > 0 && option.approved)
      .map((option) => {
        this.voteSum += option.votes;

        let title = option.optionTitle;
        if (title.length > 10) title = title.substring(0, 10) + '...';

        return {
          approved: true, //only approved allowed
          optionTitle: title,
          votes: option.votes,
          _id: option._id,
        };
      });


    const pie = d3.pie<Option>().value((d: any) => d.votes);
    this.arcs = pie(this.data);
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes["options"]) {
      this.constructPie();
    }
  }

  label(title: string, votes: number) {
    return `${title} ${Math.round((votes / this.voteSum) * 100)}%`;
  }

  getColor(i: number) {
    if (i === this.arcs.length - 1 && this.colors(i + '') === this.colors('0')) {
      return this.colors((i + 1) + '');
    } else { 
      return this.colors(i + '');
    }
  }

  arcLabelTranslate(d: PieArcDatum) {
    const amount = d3
      .arc<PieArcDatum>()
      .outerRadius(this.RADIUS - 60)
      .innerRadius(this.RADIUS - 60)
      .centroid(d);

    return `translate(${amount})`;
  }

  middlePieTranslate(d: PieArcDatum) {
    const amount = d3
      .arc<PieArcDatum>()
      .innerRadius(0)
      .outerRadius(0)
      .centroid(d);

    return `translate(${amount})`
  }

}

<div *ngIf="data.length > 0" class="w-full p-5 h-fit mx-auto">
  <svg
    class="w-1/2 h-full mx-auto"
    viewBox="0 0 400 400"
    preserveAspectRatio="xMidYMid meet"
  >
    <g transform="translate(200, 200)">
      <g
        *ngFor="let d of arcs; let i = index"
        (mouseenter)="setSlice(d.data['_id'])"
        (mouseleave)="setSlice('')"
        class="cursor-crosshair"
      >
        <path [attr.d]="arc(d)" [attr.fill]="getColor(i)" />
        <text
          [attr.transform]="arcLabelTranslate(d)"
          text-anchor="middle"
          fill="black"
          font-size="16px"
        >
          {{ label(d.data.optionTitle, d.data.votes) }}
        </text>
      </g>

      <text
        [attr.transform]="middlePieTranslate(arcs[0])"
        text-anchor="middle"
        fill="white"
        font-size="24px"
      >
        {{ voteSum + (voteSum === 1 ? " vote" : " votes") }}
      </text>
    </g>
  </svg>
</div>
