// frontend/src/welcome/CreatedPolls.tsx
import { useEffect, useState } from "react";
import CreatedBox from "./CreatedBox";
import { AlertAction } from "../hooks/useAlert";

export type Polls = { [pollId: string]: string };

interface CreatedPollsProps {
    userId: string,
    alertDispatch: React.Dispatch<AlertAction>
}

function CreatedPolls(props: CreatedPollsProps) {
    const [selected, setSelected] = useState<string[]>([]);
    const [allSelected, setAllSelected] = useState(false);

    useEffect(() => {
        if (allSelected) {
            const createdPolls = localStorage.getItem("created")
            if (!createdPolls)
                return;

            const polls: Polls = JSON.parse(createdPolls);

            setSelected(Object.keys(polls));
        } else
            setSelected([]);
    }, [allSelected])


    const toggleSelected = (e: React.FormEvent<HTMLInputElement>) => {
        const id = (e.target as HTMLInputElement).id

        for (let i = 0; i < selected.length; i++)
            if (selected[i] === id) {
                const temp = [...selected];
                temp.splice(i, 1);
                setSelected(temp);
                return;
            }

        setSelected([...selected, id]);

    }


    const deletePolls = async () => {
        const pollIds = selected.join(".");
        setAllSelected(false);
        if (pollIds) {
            const url = `${process.env.NODE_ENV !== "production" ? process.env.REACT_APP_DEV_HTTP_URL : process.env.REACT_APP_PROD_HTTP_URL}/api/polls/delete`
            await fetch(url, {
                method: "DELETE",
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ pollIds: pollIds, userId: props.userId })
            }).then(response => response.json());

            //this should find data unless the user deletes it for some reason
            const createdPolls = localStorage.getItem("created")

            if (createdPolls) {
                const trimmed: Polls = JSON.parse(createdPolls);

                selected.forEach((id) => {
                    delete trimmed[id]
                })

                if (Object.keys(trimmed).length === 0)
                    localStorage.removeItem("created")
                else
                    localStorage.setItem("created", JSON.stringify(trimmed));
            }

            props.alertDispatch({
                type: "ADD_ALERT", payload: {
                    msg: "Polls Deleted",
                    time: 2000,
                    type: "success"
                }
            })

            setSelected([])

        }
    }


    const createdPolls = localStorage.getItem("created")
    if (!createdPolls) {
        return null;
    }

    const polls: Polls = JSON.parse(createdPolls);
    
    return (
        <div className="bg-stone-600 h-fit w-5/6 mx-auto p-6 mt-8 rounded-xl shadow-xl">
            <p className="text-xl lg:text-2xl mb-4 select-none px-4 text-white">
                Your Created Polls
            </p>

            <ul className="overflow-y-auto mx-auto w-fit px-6">
                <li key="selectAll" className="h-fit flex justify-between">
                    <label htmlFor="selectAll" className="text-gray-300 select-none">
                        Select All
                    </label>
                    <input id="selectAll" 
                        checked={allSelected} 
                        onChange={() => { setAllSelected(!allSelected) }} 
                        className="border border-black ml-32" 
                        type="checkbox" 
                    />
                </li>
                
                {Object.keys(polls).reverse().map((id) =>
                    <CreatedBox
                        id={id}
                        key={id}
                        title={polls[id]}
                        toggleSelected={toggleSelected}
                        selected={selected.includes(id)}
                        checked={selected.includes(id)}
                    />)
                }
            </ul>

            {selected.length > 0 ? 
                <div className="mt-4">
                    <label className="text-red-100" onClick={deletePolls}>
                        {"Delete Selected Polls"}
                    </label>

                    <button 
                        onClick={deletePolls}
                        className="bg-red-200 rounded border border-black ml-2 px-2 text-black text-xs self-center">
                        {selected.length}
                    </button>
                </div>
            : null}
        </div>
    )
}

export default CreatedPolls;

// frontend/src/app/components/welcome/created-polls/created-polls.component.ts
import { Component, Input } from '@angular/core';
import { CreatedPoll } from '../../../types/types';
import { HttpPollService } from '../../../services/http-poll.service';
import { AlertService } from '../../../services/alert.service';

@Component({
  selector: 'created-polls',
  templateUrl: './created-polls.component.html',
})
export class CreatedPollsComponent {
  @Input() userId!: string;

  createdPolls: CreatedPoll[];

  constructor(private httpPollService: HttpPollService, private alertService: AlertService) {
    this.createdPolls = this.httpPollService.getCreatedPolls()
  }

  get pollsSelected(): number {
    return this.createdPolls.filter((p) => p.selected).length;
  }

  get isAllSelected(): boolean {
    //can find a selected poll?
    return this.pollsSelected === this.createdPolls.length;
  }

  setAll() {
    //if all selected, set all to false. otherwise, set all to true.
    const endRes = !this.isAllSelected;

    this.createdPolls.forEach((p) => {p.selected = endRes})
  }

  deletePolls() {
    const selected = this.createdPolls.filter((p) => p.selected);

    this.httpPollService.deletePolls(selected, this.userId)?.subscribe({
      next: (response) => {
        this.alertService.addAlert("Polls deleted")
        this.createdPolls = this.httpPollService.getCreatedPolls()
      },
      error: (response) => {console.log(response)},
    });
  }
  
}

<div
  *ngIf="createdPolls.length > 0"
  class="bg-stone-600 h-fit w-5/6 mx-auto p-6 mt-8 rounded-xl shadow-xl"
>
  <p class="text-xl lg:text-2xl mb-4 select-none px-4 text-white">
    Your Created Polls
  </p>

  <ul class="overflow-y-auto mx-auto w-fit px-6">
    <div
      *ngIf="pollsSelected > 0"
      class="text-white mt-2 justify-center flex px-4 py-2 rounded-xl bg-gray-600 w-fit mx-auto shadow-md"
    >
      <label htmlFor="selectAll"> Select All </label>

      <input
        class="w-4 h-4 rounded-xl ml-1 self-center"
        id="selectAll"
        type="checkbox"
        [checked]="isAllSelected"
        (click)="setAll()"
      />

      <label class="px-1 ml-6 text-red-200 pointer" (click)="deletePolls()">
        Delete Selected Polls
      </label>

      <button
        (click)="deletePolls()"
        class="bg-red-200 rounded border border-black h-fit self-center px-2 text-black text-xs"
      >
        {{ pollsSelected }}
      </button>
    </div>
    <a
      *ngFor="
        let poll of createdPolls;
        let i = index;
        trackBy: trackCreatedPolls
      "
      href="poll/{{ poll.pollId }}"
    >
      <li
        class="h-fit flex justify-between p-2 rounded mt-2 shadow-md min-w-48"
        [ngClass]="i % 2 === 0 ? 'bg-gray-600' : 'bg-gray-700'"
      >
        <label
          class="break-all cursor-pointer"
          [ngClass]="poll.selected ? 'text-red-200' : 'text-blue-200'"
        >
          {{ poll.title }}
        </label>
        <input
          type="checkbox"
          [id]="poll.pollId"
          (click)="toggleSelected(poll.pollId)"
          [checked]="poll.selected"
          class="border border-black ml-2 self-center"
        />
      </li>
    </a>
  </ul>
</div>
