// frontend/src/app/components/poll/settings/settings.component.ts
import { Component, Input } from '@angular/core';
import { EMPTY_POLL } from 'src/app/constants/constants';
import { PollDataService } from 'src/app/services/poll-data.service';
import { UserIDService } from 'src/app/services/user-id.service';
import { WsPollService } from 'src/app/services/ws-poll.service';
import { ToggleSettingEmit, PollData } from 'src/app/types/types';

@Component({
  selector: 'settings',
  templateUrl: './settings.component.html',
})
export class SettingsComponent {
  @Input() userView!: boolean;

  pollData: PollData = EMPTY_POLL;
  userId: string = '';
  anySettingActive: boolean = false;

  constructor(
    private userIdService: UserIDService,
    private pollDataService: PollDataService,
  ) {}

  ngOnInit() {
    this.pollDataService.pollData$.subscribe((pollData) => {
      if (pollData) {
        this.pollData = pollData;

        this.anySettingActive = (
          pollData.settings['disableVoting'] ||
          pollData.settings['hideVotes'] ||
          pollData.settings['limitOneVote'] ||
          pollData.settings['approvalRequired']);
        }
    });
    this.userIdService.userId$.subscribe((userId) => {
      this.userId = userId;
    });
  }

}

<div
  *ngIf="pollData.isOwner && !userView; else elseBlock"
  class="bg-slate-600 mt-4 p-3 w-fit mx-auto rounded-xl shadow-md"
>
  <h1 class="text-white text-2xl mb-2 font-semibold">Settings</h1>

  <settings-checkbox
    text="Disable Voting"
    name="disableVoting"
  />

  <settings-checkbox
    text="Hide Vote Count"
    name="hideVotes"
  />

  <settings-checkbox
    *ngIf="pollData.settings['hideVotes']"
    text="Hide Vote Count For You"
    name="hideVotesForOwner"
    [indent]="true"
  />

  <settings-checkbox
    text="Limit Users To One Vote"
    name="limitOneVote"
  />

  <settings-checkbox
    text="New Options Require Approval"
    name="approvalRequired"
  />

  <settings-checkbox
    *ngIf="pollData.settings['approvalRequired']"
    text="Auto Approve Your Options"
    name="autoApproveOwner"
    [indent]="true"
  />
</div>

<ng-template #elseBlock>
  <div
    *ngIf="anySettingActive"
    class="p-4 rounded-xl mx-auto w-fit mt-4 bg-slate-600 shadow-md"
  >
    <h1
      class="text-center text-2xl font-semibold pt-1 text-white select-none mb-3"
    >
      Settings
    </h1>

    <ul class="text-left text-white text-md">
      <li *ngIf="pollData.settings['disableVoting']">
        Adding and removing votes is disabled
      </li>
      <li *ngIf="pollData.settings['hideVotes']">Vote counts are hidden</li>
      <li *ngIf="pollData.settings['limitOneVote']">
        You may only cast one vote at a time
      </li>
      <li *ngIf="pollData.settings['approvalRequired']">
        New options require approval from the owner
      </li>
    </ul>
  </div>
</ng-template>

// frontend/src/poll/Settings.tsx
import SettingCheckBox from './SettingCheckBox';
import SettingListDisplay from './SettingListDisplay';
import { w3cwebsocket as W3CWebSocket } from "websocket";
import { PollSettings } from '../App';


interface SettingsProps {
    ws: W3CWebSocket
    isOwner: boolean
    pollId: string
    userId: string
    settings: PollSettings
}

function Settings(props: SettingsProps) {
    if (props.isOwner) {
        return (
            <div className="bg-slate-600 mt-4 p-3 w-fit mx-auto rounded-xl shadow-md">
                <h1 className='text-white text-2xl mb-2 font-semibold'>Settings</h1>
                <SettingCheckBox ws={props.ws} text="Disable Voting" name="disableVoting" indent={false} pollId={props.pollId} userId={props.userId} active={props.settings["disableVoting"]} />

                <SettingCheckBox ws={props.ws} text="Hide Vote Count" name="hideVotes" indent={false} pollId={props.pollId} userId={props.userId} active={props.settings["hideVotes"]} />

                {props.isOwner && props.settings["hideVotes"] ?
                    <SettingCheckBox ws={props.ws} text="Hide Vote Count For You" name="hideVotesForOwner" indent={true} pollId={props.pollId} userId={props.userId} active={props.settings["hideVotesForOwner"]} />
                    : null}

                <SettingCheckBox ws={props.ws} text="Limit Users To One Vote" name="limitOneVote" indent={false} pollId={props.pollId} userId={props.userId} active={props.settings["limitOneVote"]} />

                <SettingCheckBox ws={props.ws} text="New Options Require Approval" name="approvalRequired" indent={false} pollId={props.pollId} userId={props.userId} active={props.settings["approvalRequired"]} />

                {props.isOwner && props.settings["approvalRequired"] ?
                    <SettingCheckBox ws={props.ws} text="Auto Approve Your Options" name="autoApproveOwner" indent={true} pollId={props.pollId} userId={props.userId} active={props.settings["autoApproveOwner"]} />
                    : null}

            </div>)

    } else if (props.settings["disableVoting"] || props.settings["hideVotes"] || props.settings["limitOneVote"] || props.settings["approvalRequired"]) {
        return (
            <div className="p-4 rounded-xl mx-auto w-fit mt-4 bg-slate-600 shadow-md">
                <h1 className="text-center text-2xl font-semibold pt-1 text-white select-none mb-3">Settings</h1>

                <ul className="text-left">
                    <SettingListDisplay text="Adding and removing votes is disabled" display={props.settings["disableVoting"]} />
                    <SettingListDisplay text="Vote counts are hidden" display={props.settings["hideVotes"]} />
                    <SettingListDisplay text="You may only cast one vote at a time" display={props.settings["limitOneVote"]} />
                    <SettingListDisplay text="New options require approval from the owner" display={props.settings["approvalRequired"]} />
                </ul>
            </div>
        )

    } else 
        return null;
}

export default Settings;
