// frontend/src/app/components/poll/voting/dropdown/dropdown-option/dropdown-option.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FilterMethod, SortingMethod } from 'src/app/types/types';

@Component({
  selector: 'dropdown-option',
  templateUrl: './dropdown-option.component.html',
})
export class DropdownOptionComponent {
  @Input() disabled?: boolean;
  @Input() selected!: boolean;
  @Input() name!:  SortingMethod | FilterMethod;

  @Output() setSelectedMethod = new EventEmitter<string>();

  set() {
    this.setSelectedMethod.emit(this.name);
  }

}

<div *ngIf="disabled; else elseBlock" class="block text-center w-full text-gray-400">
    {{ name }}
</div>

<ng-template #elseBlock>
    <div (click)="set()" 
        class="cursor-pointer block w-full text-center"
        [ngClass]="selected ? 'text-sky-300' : 'text-white'">
            {{ name }}
    </div>
</ng-template>

// frontend/src/misc/DropdownOption.tsx
import React from "react"

interface DropdownOptionProps {
    selected: boolean
    disabled: boolean
    name: string
    setSortingMethod: (str: string) => void
}
const DropdownOption = (props: DropdownOptionProps) => {
    const setSorting = (e: React.MouseEvent<HTMLDivElement>) => {
        e.stopPropagation();
        props.setSortingMethod(props.name);
    }

    if (props.disabled)
        return (
            <div className={"block text-center w-full text-gray-400"}>
                {props.name}
            </div>)
    else
        return (
            <div onClick={setSorting} className={"cursor-pointer block w-full text-center " + (props.selected ? "text-sky-300" : "text-white")}>
                {props.name}
            </div>)

}

export default DropdownOption;
